# Makefile for the TU58 Device Driver project - RLA [12-Aug-94]

CC=bcc -c -ms -Z -O -Ol -Oe
ASM=tasm -mx

DEPS=cprint.c driver.c sd.c sdmm.c cprint.h diskio.h driver.h integer.h sd.h standard.h 

all: xtsd.sys xtsd186.sys

.asm.obj:
   $(ASM) $*

xtsd.sys: header.obj $(DEPS)
   $(CC) cprint.c
   $(CC) sd.c
   $(CC) sdmm.c
   $(CC) driver.c
   tlink -t -m -s -n header cprint sd sdmm driver, $@

xtsd186.sys: header.obj $(DEPS)
   $(CC) -1 -DUSE186 cprint.c
   $(CC) -1 -DUSE186 sd.c
   $(CC) -1 -DUSE186 sdmm.c
   $(CC) -1 -DUSE186 driver.c
   tlink -t -m -s -n header cprint sd sdmm driver, $@

clean:
   del *.obj
   del *.map
   del *.sys

header.obj: header.asm
